if((NOT DEFINED Boost_INCLUDE_DIRS) OR (Boost_INCLUDE_DIRS STREQUAL ""))
	find_package(Boost REQUIRED)
endif()

if(USE_OPENMP)
	find_package(OpenMP REQUIRED)
	add_compile_options(${OpenMP_CXX_FLAGS})
endif()

if(USE_OPENCV AND (DEFINED ANDROID_NDK))
	set(OpenCV_INCLUDE_DIRS E:/OpenCV-android-sdk/sdk/native/jni/include)
	set(OpenCV_LIBRARY_DIRS E:/OpenCV-android-sdk/sdk/native/libs/${ANDROID_ABI})
	set(OpenCV_LIBS opencv_java3)
else()
	find_package(OpenCV REQUIRED)
endif()