if((NOT DEFINED Boost_INCLUDE_DIRS) OR (Boost_INCLUDE_DIRS STREQUAL ""))
	find_package(Boost REQUIRED)
endif()

if (NOT DEFINED Boost_INCLUDE_DIRS)
	set(Boost_INCLUDE_DIRS C:/Tools/vcpkg/installed/x64-windows/include)
endif()

if(USE_OPENMP)
	find_package(OpenMP REQUIRED)
	add_compile_options(${OpenMP_CXX_FLAGS})
endif()

if(USE_OPENCV)
	find_package(OpenCV)
		message(WARNING "OPENCV_FOUND: ${OPENCV_FOUND}")
	if(NOT OPENCV_FOUND)
		message(WARNING "Not Found installed OpenCV, use mannual configuration.")

		set(OpenCV_INCLUDE_DIRS E:/OpenCV-android-sdk/sdk/native/jni/include)
		set(OpenCV_LIBRARY_DIRS E:/OpenCV-android-sdk/sdk/native/libs/${ANDROID_ABI})
		set(OpenCV_LIBS opencv_java4)
	endif()
	message(STATUS "OpenCV_INCLUDE_DIRS: ${OpenCV_INCLUDE_DIRS}")
	message(STATUS "OpenCV_LIBRARY_DIRS: ${OpenCV_LIBRARY_DIRS}")
	message(STATUS "OpenCV_LIBS: ${OpenCV_LIBS}")
endif()
